data:
  data_dir: "./data/nih-chest-xrays"
  batch_size: 8
  num_workers: 4
  num_classes: 14
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15

training:
  epochs: 20
  learning_rate: 0.0001
  early_stopping: 5

models:
  resnet101:
    image_size: 512
  densenet121:
    image_size: 512
  efficientnet_b7:
    image_size: 600